// src/routes/recipe/[id]/+page.svelte
<script lang="ts">
	import type { PageProps } from './$types';
	import * as m from '$lib/paraglide/messages.js';
	import placeholder from '$lib/assets/placeholder.png';

	const { data }: PageProps = $props();
</script>

<section class="flex flex-col gap-4 pb-8">
	<div class="breadcrumbs text-sm">
		<ul>
			<li class="text-accent"><a href="/">{m['recipe.breadcrumbs.my_recipes']()}</a></li>
			<li class="text-primary">{data.recipe.name}</li>
		</ul>
	</div>

	<h1 class="text-xl font-bold">{data.recipe.name}</h1>

	<img
		class="h-48 w-full object-cover md:h-122"
		src={data.recipe.coverUrl ?? placeholder}
		alt="Recipe cover"
	/>

	<div class="flex flex-col gap-2 text-primary">
		<h2 class="font-bold">{m['recipe.ingredients']()}</h2>
		<ul class="list-inside list-disc">
			{#each data.recipe.ingredients as ingredient, index (index)}
				<li>{ingredient}</li>
			{/each}
		</ul>
	</div>

	<div class="flex flex-col gap-2 text-primary">
		<h2 class="font-bold">{m['recipe.instructions']()}</h2>
		<ol class="list-inside list-decimal">
			{#each data.recipe.instructions as instruction, index (index)}
				<li>{instruction}</li>
			{/each}
		</ol>
	</div>
</section>

// pages/recipes/[id].vue
<script setup lang="ts">
const route = useRoute()

const { id } = route.params;

const { data: recipe } = useFetch(`/api/recipe/${id}`);
</script>

<template>
    <UContainer v-if="recipe" class="mt-12">
        <h1 class="text-center font-bold text-2xl">{{ recipe.title }}</h1>
        <div class="flex gap-2">
            <img :src="recipe.img" :alt="`${recipe.title} cover image`" class="w-48 h-48" />
        </div>

        <div class="mt-4">
            <h3 class="font-semibold text-xl">Ingredients</h3>

            <ul class="list-disc list-inside">
                <li v-for="(ingredient) in recipe.ingredients">
                    {{ ingredient }}
                </li>
            </ul>
        </div>

        <div class="mt-4">
            <h3 class="font-semibold text-xl">Instructions</h3>

            <ul class="list-decimal list-inside">
                <li v-for="(instruction) in recipe.instructions">
                    {{ instruction }}
                </li>
            </ul>
        </div>
    </UContainer>

    <UContainer v-else class="mt-12">
        No recipes found
    </UContainer>
</template>
